name: Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run ESLint with Reviewdog
        run: |
          npx eslint . --format json > eslint-report.json
          reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error < eslint-report.json
